# Generated by Django 4.0.2 on 2022-02-27 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField()),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('importance', models.IntegerField(choices=[(1, 'Ridicata'), (2, 'Medie'), (3, 'Scazuta')])),
            ],
        ),
    ]
